# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8af0dd30089e849cba70e383b0b5dd95a9b5a7383eacf078fd32992bf867baf68c74df3a029fde668d7dfaa23bd8c50c4564862d6f2717f97961231f978806d8

test:
  secret_key_base: e3fbd10a0eb218e862c9189377327cb3a8624f27dfc564e65b33d4eb5f602e5232e9ad3c2d9a50f067772c1c2d2e606ea1f16ff7d6c322ce194f0c7bd63a1fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
